---
- name: "Set authorized key for user {{ansible_ssh_user}} copying it from current user"
  authorized_key:
    user: "{{ansible_ssh_user}}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"